### ISSUE TITLE
Wrong file permission - crashing

### ISSUE THREAD

**Issue by RandomUsername12222** [fredldotme/vscodium-click-packaging#3]
Target : samsung s10+
Reproduce: Open app. Expect it to open
Expected behaviour: App open
Current behaviour: App crash

Logs:
`[11445:0311/054334.872468:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/click.ubuntu.com/codium.vscodium.com/1.65.0/chrome-sandbox is owned by root and has mode 4755`

I did change that file permission but its still showing that error.

**Comment by BohdanQQ** [comment]
This might help:

https://github.com/fredldotme/vscodium-click-packaging/pull/1#issue-1164497003

**Comment by RandomUsername12222** [comment]
@BohdanQQ Completly didn't notice pull requests. Sorry and thx
